export let Movies = {
    'The Take Down': {
        genre: 'action',
        description: 'When Jack, a hit man from London, gets given his life back and the opportunity to save his daughter, it becomes a race against time to kill or be killed.',
        video_url: 'SPNJKnFlJSg',
        rating: 33,
        img_url: 'https://m.media-amazon.com/images/M/MV5BZTBlNDFkZmItYmUwMS00MzhhLTg4MDktNTk0NTIzN2IzNTA5XkEyXkFqcGdeQXVyNjgxMzY0MzA@._V1_UY268_CR1,0,182,268_AL_.jpg',
        runtime: '1:39:54',
        showtimes: ['3:00:00 AM',
        '7:00:00 AM',
        '9:00:00 AM',
        '1:00:00 PM',
        '3:00:00 PM',
        '6:00:00 PM',
        '8:00:00 PM']
    },
    'Beta Test': {
        genre: 'action',
        description: "Champion gamer Max Troy discovers events in a new video game are being mirrored in the real world, and must join forces with the game's protagonist, Orson Creed, to unravel the conspiracy before the game's sinister plot overwhelms the city.",
        video_url: 'roB7oEMk168',
        rating: 80,
        img_url: 'https://m.media-amazon.com/images/M/MV5BODdlMjU0MDYtMWQ1NC00YjFjLTgxMDQtNDYxNTg2ZjJjZDFiXkEyXkFqcGdeQXVyMTU2NTcxNDg@._V1_UX182_CR0,0,182,268_AL_.jpg',
        runtime: '1:27:56',
        showtimes: ['3:00:00 AM',
        '7:00:00 AM',
        '9:00:00 AM',
        '12:00:00 PM',
        '2:00:00 PM',
        '5:00:00 PM',
        '7:00:00 PM']
    },
    'Henrys Crime': {
        genre: 'comedy',
        description: "Released from prison for a crime he didn't commit, an ex-con targets the same bank he was sent away for robbing.",
        video_url: 'Doo3UivJhtc',
        rating: 60,
        img_url: 'https://m.media-amazon.com/images/M/MV5BMjI4MzM4OTY3MF5BMl5BanBnXkFtZTcwOTMzMjI3NA@@._V1_UX182_CR0,0,182,268_AL_.jpg',
        runtime: '1:47:48',
        showtimes: ['3:00:00 AM',
        '7:00:00 AM',
        '9:00:00 AM',
        '1:00:00 PM',
        '3:00:00 PM',
        '6:00:00 PM',
        '8:00:00 PM']
    },
    'Temple': {
        genre: 'horror',
        description: 'Three American tourists follow a mysterious map deep into the jungles of Japan searching for an ancient temple. When spirits entrap them, their adventure quickly becomes a horrific nightmare.',
        video_url: 'wBgFbp6LKCs',
        rating: 36,
        img_url: 'https://m.media-amazon.com/images/M/MV5BNmVhNTMyZTUtOTkwYS00NzU3LTg1NDEtMTQ5ZGNiNWE1YWYyXkEyXkFqcGdeQXVyMTM2MzgyOTU@._V1_UX182_CR0,0,182,268_AL_.jpg',
        runtime: '1:18:05',
        showtimes: ['3:00:00 AM',
        '7:00:00 AM',
        '9:00:00 AM',
        '1:00:00 PM',
        '3:00:00 PM',
        '6:00:00 PM',
        '8:00:00 PM']
    },
    'Beyond The Trek': {
        genre: 'scifi',
        description: 'A deep space mining vessel has been adrift for two years. It is suspected the crew brutally killed each other, but the reason for the bloodbath is unknown. A rescue crew is sent to find if there are any survivors, what happened and why.',
        video_url: '2xL-zwKVr80',
        rating: 44,
        img_url: 'https://m.media-amazon.com/images/M/MV5BZDc2M2MyZDMtMDhjNi00Njk4LThjODktZDUxY2ZjOTQxODMyXkEyXkFqcGdeQXVyMjg1MDczNg@@._V1_UX182_CR0,0,182,268_AL_.jpg',
        runtime: '1:30:07',
        showtimes: ['3:00:00 AM',
        '7:00:00 AM',
        '9:00:00 AM',
        '1:00:00 PM',
        '3:00:00 PM',
        '6:00:00 PM',
        '8:00:00 PM']
    },
    'Runaway Romance': {
        genre: 'romance',
        description: 'A reality TV star leaves Hollywood and finds herself in Amish country where she must decide between staying in her newfound reality or returning to her old one.',
        video_url: 'D-KWNUesPvI',
        rating: 61,
        img_url: 'https://m.media-amazon.com/images/M/MV5BYjQ0OTAzMTUtOTQ3Ni00OTg1LThmMWQtODY5NjA4OGJkMDhmXkEyXkFqcGdeQXVyMjAzNjAzMQ@@._V1_UY268_CR4,0,182,268_AL_.jpg',
        runtime: '1:30:14',
        showtimes: ['3:00:00 AM',
        '7:00:00 AM',
        '9:00:00 AM',
        '1:00:00 PM',
        '3:00:00 PM',
        '6:00:00 PM',
        '8:00:00 PM']
    },
}